# -*- coding: utf-8 -*-
"""Linear_regression_sum_of_two.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSZrbah7xr5Om-nIH7B1EUm9j3yRgMwN
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#Now loading the dataset....
from google.colab import files
uploaded = files.upload()

data = pd.read_csv("sum_dataset.csv")

#Just displaying the dataset
print(data.head())

X = data[['A', 'B']]
y = data['Sum']

#Splitting the data for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

#calling model object
model = LinearRegression()

#training the model
model.fit(X_train, y_train)

#predciting??
predictions = model.predict(X_test)

#comparing actual and predicted values
result = pd.DataFrame({'Actual' : y_test, 'Predicted' : predictions})
print(result.head(10))

#Predicting results by taking input from the user
num1 = int(input("Enter the First Number : "))
num2 = int(input("Entter the Second Number : "))
predictions = model.predict([[num1, num2]])

print("Predicted Sum = ", predictions[0])